language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

after_success:
  - ./gradlew jacocoTestReport coveralls

notifications:
  email: false
  slack:
    rooms:
      secure: yeIVBmpZzSjIGU2c+1O8q79LDoxmQNJiqVs52PCfUdRGfh2f/1tsInU0ru4M/LC984RQuVhhRVitHCImBec/sB93W0FL2owr5oAf8G1rONY4qGBxLPeVzxXcWTpD3wBzSc+PUVR7lv05JRYbn2yRfobDEO3jHgar/OjmWpNulBBCPOGPnmZKdj4i4VVu0HtzIfsdaFyvudVVm5/duj3gikHTJsABIButsxFDC3jDSAfhYMDMlJUn1FGgOyJebJgtaMcLH9VG/oauon72cc2qAPzWJhfmY3Uqn7ZCjdZUOvT4XLm0XzQhPU6c8hqJdlOEad970iXR3KTF45piW0JSsveIntu5pefEBQeY1w4WVkfGeVeqnSLz+rbW/V8hg5tCTBs5c/s3C4O7Xu4hqAPCALRSUg/7C5HUxK2qPcjZEgFTqx0qX5KfrUGumgfe1StqqFYVG4jao0+1YNpvb9hEA4pDxnISytRfhLttVQEbH4KzNa1jr1mzb640dVs0CAkRzGTvxs4jXkSqKwmCljuO/VCw3yXstkV5VmM6BAR24MsEzk5RGxVphwkfnygqQuIVPlTtKdgClfbRzaEB2FIAb7H+gqvtIPxokQx+8t+smz3ikk6BqilxIrQqxzUsYyWqrt47+VYzKOpT83Rnb1glp1Arfj2milBAHa4rjDo8tXs=
